name: "Update Pull Request"

on: [pull_request]

jobs:
  pr_update_text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update name step
        uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          branch-regex: '.'
          lowercase-branch: true
          title-template: "[updated-by-action]"
          replace-title: false
          title-prefix-space: true
          uppercase-title: false
          body-template: "[Updated by Pull Request Updater action]"
          replace-body: false
          body-prefix-newline-count: 2
          uppercase-body: false
